// SPDX-License-Identifier: MIT
// Highly-visual educational contract code representation

export const DEBATER_VAULT_CODE_LINES = [
  /* 1 */ "// SPDX-License-Identifier: MIT",
  /* 2 */ "pragma solidity ^0.8.24;",
  /* 3 */ "",
  /* 4 */ "/**",
  /* 5 */ " * @title DebaterVault",
  /* 6 */ " * @notice Escrow Clearinghouse Sandbox for Autonomous Debates & Spectator Wagers.",
  /* 7 */ " * @dev Manages entry fees, wagers, commit-reveal consensus, and automated",
  /* 8 */ " *      payouts directly in Base. Emits reactive ledger event logs.",
  /* 9 */ " */",
  /* 10 */ "contract DebaterVault {",
  /* 11 */ "    enum MatchState { Preparing, Live, Voting, Resolved }",
  /* 12 */ "",
  /* 13 */ "    struct Match {",
  /* 14 */ "        address trainerA;",
  /* 15 */ "        address trainerB;",
  /* 16 */ "        uint256 entryFee;",
  /* 17 */ "        uint256 wagerPoolA;",
  /* 18 */ "        uint256 wagerPoolB;",
  /* 19 */ "        MatchState state;",
  /* 20 */ "        bool bettingLocked;",
  /* 21 */ "        address winner;",
  /* 22 */ "    }",
  /* 23 */ "",
  /* 24 */ "    // Match mapping & states",
  /* 25 */ "    mapping(bytes32 => Match) public matches;",
  /* 26 */ "    mapping(bytes32 => mapping(address => uint256)) public wagersA; // User wagers on A",
  /* 27 */ "    mapping(bytes32 => mapping(address => uint256)) public wagersB; // User wagers on B",
  /* 28 */ "",
  /* 29 */ "    // Commit-Reveal Vote Quorum trackers",
  /* 30 */ "    struct BlindVote {",
  /* 31 */ "        bytes32 commitHash;",
  /* 32 */ "        bool committed;",
  /* 33 */ "        bool revealed;",
  /* 34 */ "    }",
  /* 35 */ "    mapping(bytes32 => mapping(address => BlindVote)) public blindVotes;",
  /* 36 */ "    mapping(bytes32 => uint256) public voteCountA;",
  /* 37 */ "    mapping(bytes32 => uint256) public voteCountB;",
  /* 38 */ "    mapping(bytes32 => uint256) public totalRevealedVotes;",
  /* 39 */ "",
  /* 40 */ "    // Event declarations logged by the Base Ledger",
  /* 41 */ "    event MatchCreated(bytes32 indexed matchId, address indexed trainerA, address indexed trainerB, uint256 entryFee);",
  /* 42 */ "    event BetPlaced(bytes32 indexed matchId, address indexed bettor, uint8 indexed prediction, uint256 amount);",
  /* 43 */ "    event BettingLocked(bytes32 indexed matchId);",
  /* 44 */ "    event VoteCommitted(bytes32 indexed matchId, address indexed voter, bytes32 commitHash);",
  /* 45 */ "    event VoteRevealed(bytes32 indexed matchId, address indexed voter, uint8 voteSelection, bytes32 salt);",
  /* 46 */ "    event MatchResolved(bytes32 indexed matchId, address winningAgent, uint256 payoutPool);",
  /* 47 */ "",
  /* 48 */ "    // Custom Modifiers",
  /* 49 */ "    modifier onlyTrainer(bytes32 matchId) {",
  /* 50 */ "        require(msg.sender == matches[matchId].trainerA || msg.sender == matches[matchId].trainerB, \"Caller is not a trainer\");",
  /* 51 */ "        _;",
  /* 52 */ "    }",
  /* 53 */ "",
  /* 54 */ "    modifier inState(bytes32 matchId, MatchState state) {",
  /* 55 */ "        require(matches[matchId].state == state, \"Invalid match state\");",
  /* 56 */ "        _;",
  /* 57 */ "    }",
  /* 58 */ "",
  /* 59 */ "    // Constructor",
  /* 60 */ "    constructor() {}",
  /* 61 */ "",
  /* 62 */ "    // ----------------------------------------------------",
  /* 63 */ "    // STATE 1: LOBBY & PREPARATION ESCROW",
  /* 64 */ "    // ----------------------------------------------------",
  /* 65 */ "",
  /* 66 */ "    /**",
  /* 67 */ "     * @notice Enters a match by locking entry fees in escrow",
  /* 68 */ "     * @dev Vault locks both trainers' mock USDC entry fees into secure escrow.",
  /* 69 */ "     * @param matchId Unique identification hash for the debate match",
  /* 70 */ "     * @param trainerA Address representing Agent A's controller",
  /* 71 */ "     * @param trainerB Address representing Agent B's controller",
  /* 72 */ "     * @param fee Escrow amount required for training validation",
  /* 73 */ "     */",
  /* 74 */ "    // Placeholder comment to adjust line alignment",
  /* 75 */ "    // Placeholder comment to adjust line alignment",
  /* 76 */ "    // Placeholder comment to adjust line alignment",
  /* 77 */ "    // Placeholder comment to adjust line alignment",
  /* 78 */ "    // Placeholder comment to adjust line alignment",
  /* 79 */ "    // Placeholder comment to adjust line alignment",
  /* 80 */ "    // Placeholder comment to adjust line alignment",
  /* 81 */ "    // Placeholder comment to adjust line alignment",
  /* 82 */ "    // Placeholder comment to adjust line alignment",
  /* 83 */ "    // Placeholder comment to adjust line alignment",
  /* 84 */ "    function enterMatch(bytes32 matchId, address trainerA, address trainerB, uint256 fee) external payable {",
  /* 85 */ "        require(matches[matchId].state == MatchState.Preparing, \"Match already active\");",
  /* 86 */ "        require(msg.value >= fee * 2, \"Escrow must lock entry fees for both trainers\");",
  /* 87 */ "",
  /* 88 */ "        matches[matchId] = Match({",
  /* 89 */ "            trainerA: trainerA,",
  /* 90 */ "            trainerB: trainerB,",
  /* 91 */ "            entryFee: fee,",
  /* 92 */ "            wagerPoolA: 0,",
  /* 93 */ "            wagerPoolB: 0,",
  /* 94 */ "            state: MatchState.Live,",
  /* 95 */ "            bettingLocked: false,",
  /* 96 */ "            winner: address(0)",
  /* 97 */ "        });",
  /* 98 */ "        emit MatchCreated(matchId, trainerA, trainerB, fee);",
  /* 99 */ "    }",
  /* 100 */ "    function placeBet(bytes32 matchId, uint8 prediction, uint256 amount) external payable inState(matchId, MatchState.Live) {",
  /* 101 */ "        require(!matches[matchId].bettingLocked, \"Wagers are closed\");",
  /* 102 */ "        require(msg.value == amount, \"Deposit must match wager amount\");",
  /* 103 */ "        require(prediction == 1 || prediction == 2, \"Can only wager on Agent A (1) or B (2)\");",
  /* 104 */ "        ",
  /* 105 */ "        if (prediction == 1) {",
  /* 106 */ "            wagersA[matchId][msg.sender] += amount;",
  /* 107 */ "            matches[matchId].wagerPoolA += amount;",
  /* 108 */ "        } else {",
  /* 109 */ "            wagersB[matchId][msg.sender] += amount;",
  /* 110 */ "            matches[matchId].wagerPoolB += amount;",
  /* 111 */ "        }",
  /* 112 */ "        emit BetPlaced(matchId, msg.sender, prediction, amount);",
  /* 113 */ "    }",
  /* 114 */ "    // Placeholder to adjust lockBetting to line 115",
  /* 115 */ "    function lockBetting(bytes32 matchId) external onlyTrainer(matchId) inState(matchId, MatchState.Live) {",
  /* 116 */ "        matches[matchId].bettingLocked = true;",
  /* 117 */ "        matches[matchId].state = MatchState.Voting;",
  /* 118 */ "        emit BettingLocked(matchId);",
  /* 119 */ "    }",
  /* 120 */ "    // Placeholder comment to adjust line alignment",
  /* 121 */ "    // Placeholder comment to adjust line alignment",
  /* 122 */ "    // Placeholder comment to adjust line alignment",
  /* 123 */ "    function commitVote(bytes32 matchId, bytes32 commitHash) external inState(matchId, MatchState.Voting) {",
  /* 124 */ "        require(!blindVotes[matchId][msg.sender].committed, \"Already committed a blind vote\");",
  /* 125 */ "        blindVotes[matchId][msg.sender] = BlindVote(commitHash, true, false);",
  /* 126 */ "        emit VoteCommitted(matchId, msg.sender, commitHash);",
  /* 127 */ "    }",
  /* 128 */ "    // Placeholder comment to adjust line alignment",
  /* 129 */ "    function revealVote(bytes32 matchId, uint8 selection, bytes32 salt) external inState(matchId, MatchState.Voting) {",
  /* 130 */ "        BlindVote storage userVote = blindVotes[matchId][msg.sender];",
  /* 131 */ "        require(userVote.committed, \"Vote not committed\");",
  /* 132 */ "        require(!userVote.revealed, \"Vote already revealed\");",
  /* 133 */ "        require(keccak256(abi.encodePacked(selection, salt)) == userVote.commitHash, \"Invalid secret reveal credentials\");",
  /* 134 */ "        ",
  /* 135 */ "        userVote.revealed = true;",
  /* 136 */ "        totalRevealedVotes[matchId]++;",
  /* 137 */ "        ",
  /* 138 */ "        if (selection == 1) voteCountA[matchId]++;",
  /* 139 */ "        else if (selection == 2) voteCountB[matchId]++;",
  /* 140 */ "        emit VoteRevealed(matchId, msg.sender, selection, salt);",
  /* 141 */ "    }",
  /* 142 */ "    // Placeholder comment to adjust line alignment",
  /* 143 */ "    // Placeholder comment to adjust line alignment",
  /* 144 */ "    // Placeholder comment to adjust line alignment",
  /* 145 */ "    function resolveMatch(bytes32 matchId) external inState(matchId, MatchState.Voting) {",
  /* 146 */ "        Match storage m = matches[matchId];",
  /* 147 */ "        require(totalRevealedVotes[matchId] >= 1, \"Requires quorum of at least 1 verified vote\");",
  /* 148 */ "        ",
  /* 149 */ "        address winner = voteCountA[matchId] >= voteCountB[matchId] ? m.trainerA : m.trainerB;",
  /* 150 */ "        m.winner = winner;",
  /* 151 */ "        m.state = MatchState.Resolved;",
  /* 152 */ "        ",
  /* 153 */ "        uint256 totalEscrow = m.entryFee * 2;",
  /* 154 */ "        uint256 totalWagers = m.wagerPoolA + m.wagerPoolB;",
  /* 155 */ "        uint256 payoutPool = totalEscrow + totalWagers;",
  /* 156 */ "        ",
  /* 157 */ "        // Platform Fee simulation (1.5% locked in sandbox)",
  /* 158 */ "        uint256 platformFee = (payoutPool * 15) / 1000;",
  /* 159 */ "        uint256 netPayout = payoutPool - platformFee;",
  /* 160 */ "        ",
  /* 161 */ "        // Transfer prize pools to the winning trainer",
  /* 162 */ "        payable(winner).transfer(totalEscrow - (platformFee / 2));",
  /* 163 */ "        ",
  /* 164 */ "        emit MatchResolved(matchId, winner, netPayout);",
  /* 165 */ "    }",
  /* 166 */ "}"
];

export const FULL_SOL_CODE = DEBATER_VAULT_CODE_LINES.join("\n");
