export const THEME = {
  agent_a: {
    name: 'Agent Alpha (Purple)',
    color: '#a855f7',
    text: 'text-cyber-purple',
    border: 'border-cyber-purple/30',
    borderActive: 'border-cyber-purple',
    bg: 'bg-cyber-purple/10',
    glow: 'cyber-glow-purple',
    pulse: 'animate-pulse-purple',
    bulletColor: 'bg-cyber-purple',
  },
  agent_b: {
    name: 'Agent Beta (Blue)',
    color: '#3b82f6',
    text: 'text-cyber-blue',
    border: 'border-cyber-blue/30',
    borderActive: 'border-cyber-blue',
    bg: 'bg-cyber-blue/10',
    glow: 'cyber-glow-blue',
    pulse: 'animate-pulse-blue',
    bulletColor: 'bg-cyber-blue',
  },
  vault: {
    name: 'Debater Vault (Amber)',
    color: '#fbbf24',
    text: 'text-cyber-amber',
    border: 'border-cyber-amber/30',
    borderActive: 'border-cyber-amber',
    bg: 'bg-cyber-amber/10',
    glow: 'cyber-glow-amber',
    pulse: 'animate-pulse-amber',
    bulletColor: 'bg-cyber-amber',
  },
  referee: {
    name: 'Consensus Ref (Emerald)',
    color: '#10b981',
    text: 'text-emerald-400',
    border: 'border-emerald-500/30',
    borderActive: 'border-emerald-400',
    bg: 'bg-emerald-500/10',
    bulletColor: 'bg-emerald-400',
  }
};
